# Exercises for the first coaching session of KIT+

## Exercise 2: Numpy

In [ ]:
import numpy as np

Set the random seed for reproducability

In [ ]:
np.random.seed(12)

**Note:** Try to do the exercises on your own first. If you cannot find a solution or do not know a function from numpy, then you are allowed to google for it. But this exercise is meant as practise for you, so google should be your last resort. 

 1) Reverse the vector (first element becomes last)

 Expected output: `[9 8 7 6 5 4 3 2 1 0]`

In [ ]:
vec = np.arange(10)
print(f"Original Array: {vec}")

vec_rev = # your solution here
print(f"Reversed Array: {vec_rev}")

2) Find indices of non-zero elements

 Expected output: `[0, 1, 4]`

In [ ]:
arr = np.array([5,2,0,0,3,0])
non_zero_idx = # your solution here

print(non_zero_idx)

3) Create a 5x5 array with random values (from 0 to 1.0) and find the minimum and maximum values

 Expected output: `Minimum: 0.002259`, `Maximum: 0.956949`

In [ ]:
arr =  # your solution here
print(f"Array:\n{arr}")

arr_min =  # your solution here
arr_max =  # your solution here
print(f"\nMinimum: {arr_min}")
print(f"Maximum: {arr_max}")

4) Create a 5x5 matrix with row values ranging from 0 to 4

 Expected output: 
 
 ```
[[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]]
```

In [ ]:
arr = np.zeros((5,5))
rows = np.arange(5)

# your solution here

print(arr)

5) Create random vector of size 10 and replace the maximum value by 0

 Expected output: 
```
[0.67145265 0.47122978 0.8161683  0.28958678 0.73312598 0.70262236
 0.32756948 0.33464753 0.         0.62458211]
```

In [ ]:
arr = # your solution here
print(arr)

# your solution here
print(arr)

6) Create a 8x8 matrix and fill it with a checkerboard pattern

 Expected output: 
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```



In [ ]:
arr = np.zeros((8,8),dtype=int)

# your solution here

print(arr)

7) Normalize a 5x5 random matrix

 Expected output: 
 
The mean of the normalized matrix will be 0 and the standard deviation will be 1

In [ ]:
arr = # your solution here
print(f"Original array:\n{arr}")

arr_norm = # your solution here
print(f"\nNormalized array:\n{arr_norm}")
print(f"\nMean: {round(np.mean(arr_norm), 8)}")
print(f"\nStandard deviation: {np.std(arr_norm)}")